language: haskell
ghc: [ "7.8" ]
before_install:
  - sudo apt-get install libgsl0-dev liblapack-dev libatlas-base-dev
  - cabal install happy alex
  - cabal install --only-dependencies
install:
  - cabal build exe:camfort
script:
  - cabal test
