flags: {}
extra-package-dbs: []
packages:
- location: '.'
- location: ../fortran-src
  extra-dep: true
- location: ../language-while
extra-deps:
- fortran-src-0.2.0.1
- partial-order-0.1.2.1
- sbv-7.1
- vinyl-0.6.0
- union-0.1.1.2
resolver: lts-8.23
