resolver: lts-5.5

# Local packages, usually specified by relative directory name
packages:
- '.'
- '../language-fortran'
- '../fortran-src'

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

