flags: {}
extra-package-dbs: []
packages:
- location: '.'
- location: ../fortran-src
  extra-dep: true
- location: ../language-while
- location: ../sbv
  extra-dep: true
extra-deps:
- fortran-src-0.2.0.1
- partial-order-0.1.2.1
- sbv-7.2
- vinyl-0.6.0
- union-0.1.1.2
resolver: lts-8.24
