resolver: lts-5.5

# Local packages, usually specified by relative directory name
packages:
- '.'
- '../language-fortran'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
#extra-deps:
#- language-fortran-0.4

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

